# Se invoca EXPLÍCITAMENTE en el VPS:
# docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build

services:
  strapi:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.strapi.rule=Host(`admin.tudominio.com`)"
      - "traefik.http.routers.strapi.entrypoints=websecure"
      - "traefik.http.routers.strapi.tls.certresolver=letsencrypt"
      - "traefik.http.services.strapi.loadbalancer.server.port=1337"

  frontend:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`tudominio.com`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
