# Se invoca EXPLÍCITAMENTE en el VPS:
# docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build

services:
  strapi:
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.strapi.rule=Host(`45.93.136.220`) && PathPrefix(`/admin`)"
    - "traefik.http.routers.strapi.entrypoints=web"

  frontend:
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.frontend.rule=Host(`45.93.136.220`)"
    - "traefik.http.routers.frontend.entrypoints=web"
