services:
  strapi:
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.strapi.rule=Host(`45.93.136.220`) && PathPrefix(`/admin`)"
    - "traefik.http.routers.strapi.entrypoints=web"
    - "traefik.http.services.strapi.loadbalancer.server.port=1337"
    - "traefik.docker.network=proxy-network"

  frontend:
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.frontend.rule=Host(`45.93.136.220`)"
    - "traefik.http.routers.frontend.entrypoints=web"