services:
  postgres:
    image: postgres:16-alpine
    container_name: news_platform_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  strapi:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: news_platform_strapi
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./volumes/strapi-uploads:/app/public/uploads
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - internal
      - proxy-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        API_URL: ${API_URL}
    env_file:
      - .env
    container_name: news_platform_frontend
    restart: unless-stopped
    depends_on:
      - strapi
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
  internal:
    driver: bridge
