services:
  strapi:
    build:
      target: development
    container_name: news_dev
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/dist
    ports:
      - "1337:1337"
    env_file:
      - .env
    environment:
      - CHOKIDAR_USEPOLLING=true
